#!/usr/bin/env python3
#
# Main CLI function that calls other bibeasy sub-functions.
#
# Author: Julien Cohen-Adad

# TODO: add feature to merge several subtypes into single subtype
# TODO: add feature to merge multiple googlesheet sources (e.g. Julien and Nikola)
# TODO: add feature to separate conference papers
# TODO: Add * for supervised students

import fileinput
from argparse import ArgumentError, ArgumentParser
from pathlib import Path

import coloredlogs

import bibeasy.gsheet as bibsheet
import bibeasy.utils as bibutils

PUBTYPES = ['article', 'nonreferred', 'conf-article', 'conf-proc', 'talk', 'bookchapter', 'patent', 'media', 'nikola']

# == ArgParse Helpers == #
def file_which_exists(arg_val: str):
    """
    ArgParse argument parses which confirms that the provided file both exists, and is a file
    (or symlink to a valid file)
    """
    ret_val = Path(arg_val)
    if not ret_val.exists():
        raise ValueError(f"Path '{arg_val}' does not exist!")
    if not ret_val.is_file():
        raise ValueError(f"Path '{arg_val}' is not a valid file or link to a valid file!")

def parse_input_refs(val: str):
    """
    Input references can either be a file, or a standalone reference, and thus need to be parsed in a unique manner
    """
    # If this command is a valid file, treat each line in the file as a new entry
    if Path(val).exists() and Path(val).is_file():
        val = fileinput.input(val)
    # Return the result
    return val

def flatten_input_refs(init_vals: list):
    """
    As input refs can contain a mix of both standalone references AND lists of references (pulled from files), we
    need to flatten it before passing it on to the rest of the program to avoid later errors.
    """
    new_vals = []
    for v in init_vals:
        # If it's a string, it's a raw ID and should just be appended to the list
        if isinstance(v, str):
            new_vals.append(v)
        # Otherwise, its data pulled from a file, and we should extend the list with its contents
        else:
            new_vals.extend([x.replace('\n', '') for x in v])
    return new_vals


# == CLI Argument Parsing == #
def get_parameters():
    parser = ArgumentParser(
        description="This script is used to format publications from GoogleSheet, and for doing cross-referencing "
                    "publication index between GoogleSheet and the XML-generated Canadian Common CV (CCV).",
        epilog="""\
Example usage:
--------------

Format GoogleSheet references for Word:
bibeasy -o publis.docx

Remove publication older than 2015:
bibeasy -o publi.docx -y 2015

Format citation in APA style.
bibeasy -o publi.docx -st APA

Only keep entries with 'x' for the column IVADO17.
bibeasy -o publi.docx -f IVADO17  # Only keep entries with 'x' for the column IVADO17.

Format for NeuroPoly's website (reverse order, re-download Gsheet, combined in single doc, check authorized labels):
bibeasy -o publis.md --type article conf-article --reverse --freshen-cache --combine --check-labels

Display reference from input list:
bibeasy -i [J34, J67, C124]
bibeasy -i input.txt

Cross-reference publication index between GoogleSheet and CCV
bibeasy -x REF.XML

Replace GoogleSheet by CCV index in input text, excluding refs older than 2014:
bibeasy -x REF-CCV.XML -i INPUT.TXT -y 2014

Replace CCV by most recently updated GoogleSheet index in input text, sort replaced references, using the most recent version latest data:
bibeasy --freshen-cache -x REF-CCV.XML -i INPUT.TXT -g -s

Only output a list of CCV publications that correspond to the filter tag FILTER.
bibeasy -x REF-CCV.xml -f FILTER

Convert reference ID from one CCV version to another CCV version.
bibeasy -x REF-CCV-SRC.XML --xml-dest REF-CCV-DEST.XML
""",
        formatter_class=bibutils.SmartFormatter)
    parser.add_argument("-S", "--sync",
                        help="Copy contents of GoogleSheet into CCV XML file.",
                        action='store_true')
    parser.add_argument("-c", "--freshen-cache",
                        help="Redownload cached GoogleSheet.",
                        action='store_true')
    parser.add_argument("-x", "--xml",
                        help="Path to an XML file (generated by CCV website) which should be processed.",
                        required=False,
                        type=file_which_exists)
    parser.add_argument("-xd", "--xml-dest",
                        help="Path to an XML destination file that will be used to match against another XML "
                             "(defined by '-x' prior).",
                        required=False,
                        type=file_which_exists)
    parser.add_argument("-i", "--input", dest='input_refs',
                        help="A list of reference IDs and/or files containing reference IDs (one per line) to be used "
                             "or filtered.",
                        nargs='+',
                        type=parse_input_refs,
                        required=False)
    parser.add_argument("-g", "--to-gsheet",
                        help="Convert reference index from CCV to GoogleSheet (instead of the default behaviour: "
                             "GoogleSheet to CCV).",
                        action='store_true')
    parser.add_argument("-t", "--type",
                        help="Publication type",
                        nargs='+',
                        required=False)
    parser.add_argument("-o", "--output",
                        help="Text file to output with converted fields in the following format: [3], [5]. The "
                             "extension will determine how to format the publication list. Choices are: "
                             "'md' for NeuroPoly's website; 'docx' for word-formatted CV. Example: '-o publis.docx'",
                        type=Path,
                        required=False)
    parser.add_argument("-st", "--style",
                        help="Citation syle.",
                        choices=['APA', 'custom', 'talk'],
                        default='custom')
    parser.add_argument("-cb", "--combine",
                        help="Combine all reference types into a single document.",
                        action='store_true')
    parser.add_argument("-f", "--filter",
                        help="Name of a column in the PUBLIS-GSHEET file, which has an 'x' for each row that should be "
                             "selected and listed in the terminal output, with format: [3, 5, 14]",
                        required=False)
    parser.add_argument("-y", "--min-year",
                        help="Only select references that are superior or equal to the specified year.",
                        type=int,
                        required=False)
    parser.add_argument("-r", "--reverse",
                        help="Reverse sorting of GoogleSheet list.",
                        action='store_true')
    parser.add_argument("-s", "--sort-refs",
                        help="Sort references after replacement.",
                        action='store_true')
    parser.add_argument("-l", "--labels",
                        help="Location of labels_publication.txt",
                        type=str,
                        required=False)
    parser.add_argument("-cl", "--check-labels",
                        help="If a 'Labels' column is present, check if they correspond to labels defined in: "
                             "https://github.com/neuropoly/neuro.polymtl.ca/blob/master/publications/label_definitions.md"
                             "Note that his only concerns the formatting for NeuroPoly's website.",
                        action='store_true')
    parser.add_argument("-v", "--verbose",
                        help="Full verbose (for debugging).",
                        action='store_true')
    return parser.parse_args()


def main():
    args = get_parameters()

    # Initialize colored logging
    # Note: coloredlogs.install() replaces logging.BasicConfig()
    if args.verbose:
        coloredlogs.install(fmt='%(message)s', level='DEBUG')
    else:
        coloredlogs.install(fmt='%(message)s', level='INFO')

    # If a set of input references was provided, make sure that it is 1D (as files can make it a list of lists)
    if args.input_refs:
        input_refs = flatten_input_refs(args.input_refs)
    # Otherwise, set input-refs to None so later code can recognize that it should not be considered
    else:
        input_refs = None

    # Read XML file (CCV references)
    if args.xml:
        df_ccv = bibutils.xml_to_df(args.xml)

    # If second XML is provided, compare two versions
    if args.xml_dest:
        df_dest = bibutils.xml_to_df(args.xml_dest)
        bibutils.replace_ref_in_text(df_ccv, df_dest, input_refs, args.sort_refs)

    # Otherwise, do something else
    else:
        # Fetch GoogleSheet publication records
        df_csv = bibsheet.gsheet_to_df(args)

        if args.sync:
            if not args.xml:
                raise ArgumentError("--sync needs to be used with -x")

            bibutils.sync(df_csv, args.xml)
            return

        # Find matching refs between GoogleSheet and CCV publications
        if args.xml:
            bibutils.find_matching_ref(df_csv, df_ccv, args.type)

            # Replace references between GoogleSheet and CCV
            if input_refs:
                if args.to_gsheet:
                    bibutils.replace_ref_in_text(df_ccv, df_csv, input_refs, args.sort_refs)
                else:
                    bibutils.replace_ref_in_text(df_csv, df_ccv, input_refs, args.sort_refs)

        else:
            if input_refs:
                bibutils.display_ref(df_csv, input_refs)

        # Write GoogleSheet into formatted text
        if args.output:
            bibutils.csv_to_txt(df_csv, args)


if __name__ == '__main__':
    main()
